---
types:
    - key: USER
      isApp: true
      isAbstract: false
      icon: person_outline
      name: { en: "User" }
      links:
            - key: USER.ORDERS
              builderType: NEW
              name: { en: "Orders" }
              icon: assignment
              typeKey: PROVIDER.SERVICE
              max: 1
            - key: USER.VIDEOS
              builderType: SEARCH
              name: { en: "Video" }
              icon: video_library
              typeKey: VIDEO
              max: 1
    - key: PROVIDER.SERVICE
      isApp: true
      isAbstract: false
      icon: assignment
      name: { en: "Service" }
      dataSpec: |
                {
                "Provider": {
                    "type": "object",
                    "properties": {
                        "wirelessService": {
                            "title": "Wireless service",
                            "type": "boolean"
                        },
                        "broadbandInternet": {
                            "title": "Broadband Internet",
                            "type": "boolean"
                        },
                        "IPTV": {
                            "type": "object",
                            "properties": {
                                "seTopBox": {
                                    "title": "set-top box",
                                    "type": "boolean"
                                },
                                "wirelessRouter": {
                                    "title": "wireless router",
                                    "type": "boolean"
                                },
                                "basicTVService": {
                                    "title": "basic TV service",
                                    "type": "boolean"
                                },
                                "internetConnectivity": {
                                    "title": "wireless router",
                                    "type": "boolean"
                                },
                                "VODFormat": {
                                    "title": "video on demand: category",
                                    "type": "string",
                                    "enum": [
                                        "standart",
                                        "high-definition"
                                    ]
                                },
                                "VODDate": {
                                    "title": "video on demand: date",
                                    "type": "string",
                                    "format": "date"
                                }
                            }
                        }
                    }
                }
                }
    - key: VIDEO
      isApp: true
      isAbstract: false
      icon: video_library
      name: { en: "Video" }
      ratings:
       - key: VIDEO-RATING
         name: { en: "Rate the video" }
         style: 5STARS
      attachments:
       - key: VIDEO.IMAGE
         name: { en: "Video image" }
         contentTypes:
                - 'image/gif'
                - 'image/jpeg'
                - 'image/png'
                - 'image/tiff'
      dataSpec: |
                {
                    "type": "object",
                    "properties": {
                        "category": {
                            "title": "Category",
                            "type": "string"
                        }
                    }
                }
